MCQMCIntegration: MCQMCIntegration Namespace Reference
MCQMCIntegration Namespace Reference
Data Structures
class DigitalNet
Digital Net class for Quasi Mote-Carlo Method.
class DigitalNet< uint64_t >
Digital Net class for Quasi Mote-Carlo Method.
struct MCQMCResult
Result Structure of Numeric Integration.
class OnlineVariance
Enumerations
enum DigitalNetID { NX = 0, SOBOL = 1, NXLW = 3, SOLW = 4 }
ID of pre-defined Digital Net.
Functions
uint32_t getSMax (DigitalNetID id)
get maximum number of pre-defined digital net dimension s.
uint32_t getSMin (DigitalNetID id)
get minimum number of pre-defined digital net dimension s.
uint32_t getMMax (DigitalNetID id, uint32_t s)
get maximum number of pre-defined digital net F2 dimension m.
uint32_t getMMin (DigitalNetID id, uint32_t s)
get minimum number of pre-defined digital net F2 dimension m.
const std::string getDigitalNetName (uint32_t index)
template<typename I , typename R , typename D >
MCQMCResult monte_carlo_integration (uint32_t s, uint32_t m, uint32_t N, I &integrand, R &rand, D &dist, int probability=99)
template<typename I , typename D >
MCQMCResult quasi_monte_carlo_integration (uint32_t N, I &integrand, D &digitalNet, int probability=99)
template<typename I >
MCQMCResult quasi_monte_carlo_integration (uint32_t N, I &integrand, DigitalNetID digitalNetId, uint32_t s, uint32_t m, int probability)
Enumeration Type Documentation
DigitalNetID
enum MCQMCIntegration::DigitalNetID
ID of pre-defined Digital Net.
Enumerator
NX
Niederreiter-Xing Point Set.
SOBOL
Sobol Point Set up to dimension 21201.
NXLW
Niederreiter-Xing point set of Low WAFOM.
SOLW
Sobol point set of Low WAFOM.
Function Documentation
getDigitalNetName()
const std::string MCQMCIntegration::getDigitalNetName (uint32_t index)
getMMax()
uint32_t MCQMCIntegration::getMMax (DigitalNetID id, uint32_t s)
get maximum number of pre-defined digital net F2 dimension m.
Returns
maximum number of pre-defined digital net F2 dimension m.
getMMin()
uint32_t MCQMCIntegration::getMMin (DigitalNetID id, uint32_t s)
get minimum number of pre-defined digital net F2 dimension m.
Returns
minimum number of pre-defined digital net F2 dimension m.
getSMax()
uint32_t MCQMCIntegration::getSMax (DigitalNetID id)
get maximum number of pre-defined digital net dimension s.
Returns
maximum number of pre-defined digital net dimension s.
getSMin()
uint32_t MCQMCIntegration::getSMin (DigitalNetID id)
get minimum number of pre-defined digital net dimension s.
Returns
minimum number of pre-defined digital net dimension s.
monte_carlo_integration()
template<typename I , typename R , typename D > MCQMCResult MCQMCIntegration::monte_carlo_integration (uint32_t s, uint32_t m, uint32_t N, I & integrand, R & rand, D & dist, int probability = 99)
References MCQMCIntegration::OnlineVariance::absErr(), MCQMCIntegration::OnlineVariance::addData(), and MCQMCIntegration::OnlineVariance::getMean().
quasi_monte_carlo_integration() [1/2]
template<typename I , typename D > MCQMCResult MCQMCIntegration::quasi_monte_carlo_integration (uint32_t N, I & integrand, D & digitalNet, int probability = 99)
References MCQMCIntegration::OnlineVariance::absErr(), MCQMCIntegration::OnlineVariance::addData(), and MCQMCIntegration::OnlineVariance::getMean().
quasi_monte_carlo_integration() [2/2]
template<typename I > MCQMCResult MCQMCIntegration::quasi_monte_carlo_integration (uint32_t N, I & integrand, DigitalNetID digitalNetId, uint32_t s, uint32_t m, int probability)
References MCQMCIntegration::OnlineVariance::absErr(), MCQMCIntegration::OnlineVariance::addData(), MCQMCIntegration::OnlineVariance::getMean(), MCQMCIntegration::DigitalNet< uint64_t >::getPoint(), MCQMCIntegration::DigitalNet< uint64_t >::nextPoint(), and MCQMCIntegration::DigitalNet< uint64_t >::pointInitialize().